### ISSUE TITLE
TreeChart变量未定义

### ISSUE THREAD

**Issue by superwf** [joe-sky/flarej#10]
https://github.com/joe-sky/flarej/blob/df9d6f39e568aaf585806d7e3a901d64df1b2078/src/components/ECharts/treeChart.js#L22

TreeChart是不是应该是上面刚定义的TreeMapChart？

**Comment by joe-sky** [comment]
已修复：https://github.com/joe-sky/flarej/blob/master/CHANGELOG.md#v024-201854
